import * as path from "path";
import { House } from "../src/model";
import {
  downloadFile,
  fileExists,
  toTypeScriptLiteral,
  unzipFile,
  writeTypeScriptModule,
} from "../src/processing/script-utils";
import { extractHouses, parseOSMFile } from "../src/processing/osm-data";

/**
 * Generate output module.
 */
async function generateHousesModule(
  houses: House[],
  destinationPath: string
): Promise<void> {
  const content = `
    // Do not change this file! This code is generated by 'npm run generate:spb-houses'. 
    import {House} from "../model";
    
    export const houses: House[] = ${toTypeScriptLiteral(houses)};
  `;
  await writeTypeScriptModule(destinationPath, content);
}

type GetGeodataOptions = {
  dataDir: string;
  outputFilePath: string;
  remoteGeodataURL: string;
  geodataArchiveEntry: string;
};

/**
 * This function will regenerate houses.ts module.
 */
async function getHousesGeodata(options: GetGeodataOptions) {
  const { dataDir, outputFilePath, remoteGeodataURL, geodataArchiveEntry } =
    options;
  const geodataArchivePath = path.join(dataDir, "spb-geodata.osm.zip");
  const unzippedGeodataPath = path.join(dataDir, geodataArchiveEntry);

  if (await fileExists(outputFilePath)) {
    console.log(`Found ${outputFilePath}`);
    return;
  }

  console.log(`Downloading geodata archive from ${remoteGeodataURL}...`);
  await downloadFile(remoteGeodataURL, geodataArchivePath);
  console.log("Downloading complete!");

  console.log(
    `Unzipping archive file ${geodataArchivePath} (entry: ${geodataArchiveEntry})...`
  );
  await unzipFile(geodataArchivePath, geodataArchiveEntry, unzippedGeodataPath);
  console.log("Unzipping complete!");

  console.log(`Parsing geodata from ${unzippedGeodataPath}...`);
  const osmData = await parseOSMFile(unzippedGeodataPath);
  console.log("Parsing geodata complete!");

  console.log("Extracting houses from geodata...");
  const houses = extractHouses(osmData);
  console.log(`Extracted ${houses.length} houses.`);

  console.log(`Writing output to ${outputFilePath}...`);
  await generateHousesModule(houses, outputFilePath);
  console.log("Writing complete!");
}

getHousesGeodata({
  dataDir: "./data",
  outputFilePath: "./src/processing/spb-houses.ts",
  remoteGeodataURL: "https://stepan-anokhin.github.io/data/spb-geodata.osm.zip",
  geodataArchiveEntry: "spb-geodata.osm",
}).catch(console.error);
